### ISSUE TITLE
제목/내용 확정: 박형근

### ISSUE THREAD

**Issue by justinyoo** [devrel-kr/hacktoberfest-seoul#13]
* [x] 제목 확정
* [x] 내용 확정

**Comment by phg98** [comment]
내용은 고민중인데 아래 3가지 중에 일단 1번을 생각하고 있습니다. 의견있으면 알려주세요.
1. 왕초보 입장에서의 핵토버페스트 경험한 소감을 공유 (제일 무난할 듯)
2. 왕초보가 PR쉽게 올릴수 있는 방법 (발표날이 10/24 이니까 행사가 거의 끝나갈 시점이니 노우하우에 대한 얘기는 좀 늦은 감이 있네요)
3. 한글 웹페이지와 페북 그룹 만들고 홍보/운영한 이야기 (공감대가 좀 떨어질것 같습니다)  

아직 더 고민필요하구요.  

제목은 내용정하기 따라 달라지겠지만 대충  '왕초보의 핵토버페스트 참여기' 또는 '왕초보의 핵토버페스트 공유경험담' 이런 식으로 할까 합니다. 

슬라이드는 언제까지 만들어야 할까요?

'데모'는 어떤걸 해야 할까요?

**Comment by justinyoo** [comment]
@phg98 주제는 형근님께서 원하시는 방향으로 하시면 좋을 것 같습니다! 다만, 이번에 페북 그룹을 운영하시면서 이런저런 사건/사고(?) 등을 접하고 계신데, 그런 부분들과 결합해서 얘기하는 것은 어떨까 싶습니다.

슬라이드와 데모는 발표 전 까지만 준비하시면 되는데요, 조만간 발표자 트레이닝 세션을 준비할 예정이니 그 때 까지 얼추 준비를 하시면 좋겠습니다.

**Comment by phg98** [comment]
제목 : 왕초보의 핵토버페스트 참여 이야기   
내용 : 
* 왕초보로서 2018 핵토버페스트에 참여한 과정과 느낀점, 
* 2020년 한국어 웹페이지와 페북 그룹을 만들게된 동기와 과정, 진행 내용(사건/사고?), 느낀점
* 왕초보로서 메인테이너분들과 같은 초보자들에게 드리고 싶은 말씀
정도 입니다. 제목이 좀 밋밋해서 좀 그렇습니다. 핫핫핫핫

**Comment by phg98** [comment]
그리고 대충 이런 시놉시스?를 생각해보았는데 의견있으면 뭐라도 좋으니 알려주세욤

나는 왕초보

    제조장비회사 SW개발관리자, VisualC++ 6.0, Subversion

    웹프로그래밍은 2018년9월 부터, JS,Python,npm,pip 신세계    

           
2018 첫 참가

    왜 참가?

        티셔츠에 눈멀어서

    배운점, 느낀점

        초보자용 저장소, 번역 작업으로 완료

        깃헙 기초 사용법. 
        
        번역도 어렵다.

        메인테이너분들 리스펙!

        혼자하니까 외로워. 자랑할 데도 없어.

2019 불참

        바쁘기도 하고, 같이할 사람이 없어서

2020 사이트만들고 그룹만들어 운영

    왜 만들었나?

        회사에서 같이 할 사람 구했는데 놀랄만큼 관심이 없었다.

        찾아봤는데 없어 한번 만들어 볼까?

            You are NOBODY

            추석이니까, 자소서도 끝났고

            Justin님 믿고

            머리가 예쁘게 돼서
                            
    운영 관련

        홍보 시작
        
        첫 PR
            감동 기존 index.html, 지금 사이트, 동영상 자막, 9월에 PR

        스팸PR 사건
        
        현황 정리	

느낀점

    왕초보는 중요하다

        지식의 저주

        개구리 올챙이 적 생각못해

        스타트업 신규사용자


    초보자들 왜 참여안하나?

        바빠서! 업무, 육아, 주식, 부동산, 다른 공부 => 이건 어쩔수 없다.

        잘몰라서, 두려워서 => 이런 분은 가이드가 필요

        초보자 어려움

            1. 영어

            2. 깃, 깃헙

            3. 코딩 자신감
                            
    그래서 저장소를 가진분들께 부탁
        
        한글 저장소 찾기 쉽게 'korea' 토픽 붙였으면...

        ... 생각 정리중 ...

    그리고 관심있는 초보자 분들께 드리는 말

        나는 왜 하는가? => 왜 같이 해야 하는가?

            1. 재미로

            2. 배움

            3. 경력에 도움?

        ... 생각 정리중 ...

        같이 해요~

끗

**Comment by jiyeonseo** [comment]
대략적인 뼈대만 봐도 흥미진진하네요!! 
2020 사이트만들고 그룹만들어 운영과 느낀점의 비중을 크게 하면 좋을것 같아요! 
아무도 안해본 길이니까 많이들 흥미로워 하실것 같아요!  👍 👍 👍 👍 👍

**Comment by phg98** [comment]
다른분들 보니까 제목과 내용을 딱 깔끔하게 주셨더라구요. 그래서 저도 정리해 보았습니다.

## 제목
왕초보의 핵토버페스트 참여 이야기

## 내용 
왕초보로서 2018 핵토버페스트에 처음 참여하여 좋은 경험을 하였습니다. 그 느낌을 더 많은 분들과 함께 하고 싶어서 2020년에는 Hacktoberfest Korea (한국어 비공식) 웹페이지와 페이스북 그룹을 만들어 보았습니다. 그 동기와 과정, 느낀점 등을 함께 나누고자 합니다.

**Comment by justinyoo** [comment]
제목/내용 확정지으셨습니다! 이제 본격적으로 슬라이드를 준비해 주시면 됩니다! 우후훗!

**Comment by justinyoo** [comment]
이슈 제목 수정하고 닫겠습니다. 나머지는 별도 이슈로 빼겠습니다.
