### ISSUE TITLE
아이디어 : 한글날을 맞이하여 한국어 저장소 캠페인

### ISSUE THREAD

**Issue by phg98** [devrel-kr/hacktoberfest-seoul#20]
# 한글날을 맞이하여 한국어 저장소 캠페인

3줄 요약:
* __깃헙의 한국사용자들에게 이메일을 보내서 한글저장소에 'korean'토픽을 붙여달라고 해보자.__
* 괜찮을까용?
* 음 2줄 요약이네요...

긴 버전은 아래에

## 발단
초보자들이 기여하려고 할때 큰 두려움중에 하나가 영어입니다. 
그래서 한글로 된 저장소를 찾을 수 있으면 좋은데 현재 깃헙 저장소를 토픽 검색 해보면 
* topic:korean : 427개
* topic:korea : 114개

입니다.

반면 사용자 검색을 해보면
* location:korea : 33660명

입니다.
즉, 한국개발자로 예상되는 사람중 저장소 토픽에 'korean'을 붙인 사람은 2%정도 입니다.

## 전개
그래서, 아직 korean 토픽을 안 붙인 한글 저장소가 많을 것으로 예상되어, 
이 저장소들에 korean 토픽을 붙이는 켐페인을 하면 좋을 것 같습니다.
마침 내일이 한글날이니 시기적으로도 참 좋죠?
캠페인 방법은 홈페이지나 블로그등을 통한 '해주세요' 홍보도 좋겠습니다만, 
좀 더 적극적인 방법은 저장소 주인분들에게 이메일을 보내는 방법을 생각해 보았습니다.

## 위기
어떤 위기가 있을까요? 흐음~~~

## 절정
그래서 크롤링을 통해 location:korea 인 사용자의 이메일을 수집하고 (가능한가????)
이분들께 메일을 일괄 전송해볼까 합니다.
정중하게 취지를 설명하고 가지고 계신 저장소중에 한글로 관리중인 저장소에는 'korean' 토픽을 달아주십사 하구요.
(기술적, 법적, 윤리적 문제는 없을지 검토가 필요합니다.)
(daily-dev-blog 뉴스레터 운영자분꼐도 한번 여쭤보려구요)
기왕이면 'hacktoberfest' 토픽도 붙여달라고 해도 좋을듯요.

## 결말
그래서 보다 많은 저장소가 korean 토픽을 달아서 쉽게 검색이 가능해졌고
현재 'topic:korean topic:hacktoberfest'하면 딱 8개 나오는데 이것도 많아져서 초보자들이 기여할 저장소가 많이 늘어나서
모두 행복하게 살았답니다...
로 끝나면 좋겠습니다.

제가 초보이고 오픈소스전반을 잘 몰라서 무리한 생각을 하는건 아닐지, 이전에도 시도했던 것인지 걱정됩니다.
가감없는 의견 부탁드려요.
내일이 한글날이라 오늘 파바박 해볼까 합니다!!!

**Comment by phg98** [comment]
이메일 주소 수집 자체가 불법이군요. ㅠㅠ
기본적인것을 생각못했네요. 
아이디어를 다른 방향으로 고민해보겠습니다.하핫
----------------
누구든지 인터넷 홈페이지 운영자 또는 관리자의 사전 동의 없이 인터넷 홈페이지에서 자동으로 전자우편주소를 수집하는 프로그램이나 그 밖의 기술적 장치를 이용하여 전자우편주소를 수집하여서는 아니되며, 이를 위반시 정보통신망 이용촉진 및 정보보호 등에 관한 법률 제74조 제1항 제5호에 의해

**Comment by justinyoo** [comment]
그러면 이 이슈는 닫는 걸로! 😉
