### ISSUE TITLE
제목/내용 확정: 이보라

### ISSUE THREAD

**Issue by justinyoo** [devrel-kr/hacktoberfest-seoul#6]
* [x] 제목 확정
* [x] 내용 확정

**Comment by Violet-Bora-Lee** [comment]
# 제목
코드리뷰 vs. 번역리뷰 그 한끝차이

# 내용
100명 이상의 한국인 컨트리뷰터와 함께 '모던 JavaScript 튜토리얼' 프로젝트를 꾸려가면서 번역 프로젝트와 코드 중심 프로젝트가 그 본질은 다르지 않다고 생각하게 되었습니다. 이런 생각을 하게 된 일화들을 모던 JavaScript 튜토리얼 참여 방법을 소개하며 하나씩 사례 중심으로 나눠보려합니다.

**Comment by justinyoo** [comment]
제목/내용 확정지으셨습니다! 이제 본격적으로 슬라이드를 준비해 주시면 됩니다! 우후훗!

**Comment by justinyoo** [comment]
제목 수정하고 이 이슈는 닫겠습니다. 발표자료 준비 관련해서는 별도 이슈로 생성할께욤
